[I 190406 10:58:08 server:49] Start Success: 0.0.0.0:8888
[I 190406 10:59:49 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554519589.2537954) 25.44ms
[W 190406 10:59:58 web:2246] 405 POST /image/upload (112.65.102.172) 191.79ms
[I 190406 11:01:06 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554519666.0425718) 5.19ms
[I 190406 11:01:12 web:2246] 200 OPTIONS /api/image/upload (112.65.102.172) () () (1554519672.9614894) 0.62ms
[E 190406 11:01:13 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:01:13 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554519673.0254135) 238.27ms
[I 190406 11:01:51 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554519711.6052878) 7.21ms
[I 190406 11:02:02 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554519722.6554973) 4.95ms
[E 190406 11:02:10 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:02:10 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554519729.9514694) 56.78ms
[I 190406 11:17:21 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554520641.3721566) 4.83ms
[I 190406 11:17:34 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554520654.205506) 6.70ms
[I 190406 11:18:31 web:2246] 200 OPTIONS /api/image/upload (112.65.102.172) () () (1554520711.5285263) 0.58ms
[E 190406 11:18:31 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:18:31 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554520711.5817947) 285.51ms
[I 190406 11:20:06 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554520806.2744176) 5.07ms
[I 190406 11:20:48 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554520848.6136725) 5.07ms
[I 190406 11:21:05 base_handler:156] Expecting value: line 1 column 1 (char 0)
[E 190406 11:21:05 base_handler:222] 'group_member' is an invalid keyword argument for Product
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/product/product.py", line 36, in post
        image_2, image_3, image_4)
      File "/home/house/HouseHold/backend/house_hold/server/modules/product/model.py", line 68, in add_product
        created_at=int(time.time())
      File "<string>", line 4, in __init__
      File "/home/house/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 441, in _initialize_instance
        manager.dispatch.init_failure(self, args, kwargs)
      File "/home/house/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/home/house/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
        raise value
      File "/home/house/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 438, in _initialize_instance
        return manager.original_init(*mixed[1:], **kwargs)
      File "/home/house/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 834, in _declarative_constructor
        "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
    TypeError: 'group_member' is an invalid keyword argument for Product
[I 190406 11:21:05 web:2246] 200 POST /api/product/add (112.65.102.172) () () (1554520865.2281463) 14.89ms
[I 190406 11:21:05 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554520865.3947861) 5.21ms
[I 190406 11:24:36 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554521076.2141886) 6.70ms
[E 190406 11:24:44 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:24:44 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521084.4853756) 240.97ms
[I 190406 11:26:05 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554521165.0104492) 4.91ms
[I 190406 11:28:23 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554521303.7265034) 5.32ms
[I 190406 11:28:31 web:2246] 200 OPTIONS /api/image/upload (112.65.102.172) () () (1554521311.7599833) 0.60ms
[E 190406 11:28:31 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:28:31 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521311.8133037) 59.11ms
[E 190406 11:31:19 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:31:19 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521479.1915853) 13.52ms
[E 190406 11:31:23 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:31:23 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521482.9803984) 77.19ms
[E 190406 11:31:27 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:31:27 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521486.817867) 243.41ms
[E 190406 11:31:30 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:31:30 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521490.6443613) 61.38ms
[E 190406 11:31:35 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:31:35 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521494.9984527) 12.99ms
[E 190406 11:31:40 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:31:40 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521500.2743852) 13.14ms
[I 190406 11:37:41 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554521861.4152033) 5.02ms
[E 190406 11:37:46 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:37:46 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554521866.541295) 272.58ms
[I 190406 11:40:11 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554522011.8532557) 4.96ms
[I 190406 11:40:17 web:2246] 200 OPTIONS /api/image/upload (112.65.102.172) () () (1554522017.3100672) 0.60ms
[E 190406 11:40:17 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 11:40:17 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554522017.3632467) 51.84ms
[I 190406 11:42:25 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554522145.136933) 5.37ms
[I 190406 11:42:56 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554522176.1733742) 6.65ms
[I 190406 11:47:38 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554522458.4394157) 4.99ms
[I 190406 11:47:41 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554522461.496215) 5.34ms
[W 190406 11:48:28 web:2246] 404 GET / (139.162.83.10) 0.86ms
[I 190406 13:34:37 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554528877.2055702) 7.37ms
[I 190406 13:35:19 web:2246] 200 OPTIONS /api/image/upload (112.65.102.172) () () (1554528919.8162465) 0.63ms
[E 190406 13:35:20 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 13:35:20 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554528919.8680294) 235.50ms
[I 190406 13:37:31 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554529051.3778174) 5.10ms
[I 190406 13:37:32 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554529052.9571977) 4.94ms
[E 190406 13:37:54 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 13:37:54 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554529074.577945) 57.32ms
[I 190406 13:41:38 web:2246] 200 GET /api/category/query?page=1&protypename= (112.65.102.172) () () (1554529298.707225) 4.39ms
[I 190406 13:41:42 web:2246] 304 GET /api/category/query?page=1&protypename= (112.65.102.172) () () (1554529302.79258) 4.43ms
[I 190406 13:42:04 web:2246] 304 GET /api/product/query?name=&image_0= (112.65.102.172) () () (1554529324.4321353) 7.94ms
[E 190406 13:43:22 base_handler:215] 参数错误
    Traceback (most recent call last):
      File "/home/house/HouseHold/backend/house_hold/server/core/base_handler.py", line 212, in wrapper
        response = method(self, *args, **kwargs)
      File "/home/house/HouseHold/backend/house_hold/server/modules/image/image.py", line 14, in post
        raise ParametersError("参数错误")
    core.exception.ParametersError: 参数错误
[I 190406 13:43:22 web:2246] 200 POST /api/image/upload (112.65.102.172) () () (1554529401.82947) 238.79ms
[W 190406 13:43:53 web:2246] 404 GET http://api.ipify.org/ (122.235.191.192) 0.71ms
[I 190406 13:45:53 autoreload:202] /home/house/HouseHold/backend/house_hold/server/modules/image/image.py modified; restarting server
[I 190406 13:45:54 server:49] Start Success: 0.0.0.0:8888
